#通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是eureka server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
  server:
    enable-self-preservation: true
